name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change this if your default branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          persist-credentials: false  # Prevents storing credentials

      - name: Copy files to public repo
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git clone https://github.com/ssiza/kesnyphotography.git
          cp -R * kesny-photography-live/  # Adjust this if needed
          cd kesnyphotography
          git add .
          git commit -m "Deploying to GitHub Pages"
          git push origin main
